apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: observability
data:
  config.alloy: |
    // ⚠️ PROOF-OF-CONCEPT CONFIGURATION ⚠️
    // This configuration is for demonstration purposes only.
    // DO NOT use in production without proper security hardening!
    // 
    // Insecure settings used:
    // - tls.insecure = true
    // - No authentication
    // - Default endpoints and ports
    
    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }
      output {
        traces = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        traces = [otelcol.exporter.otlp.tempo.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "lgtm:4317"
        tls {
          insecure = true
        }
      }
    }

    // Scraping with pyroscope
    pyroscope.scrape "pprof" {
      targets = [
        {
          __address__ = "go-spikes.default:6060",
          __scheme__  = "http",
          __profile_path__ = "/debug/pprof/profile?seconds=10",
          service_name = "go-spikes",
          job = "go-spikes-cpu",
          profile_type = "cpu",
        },
        {
          __address__ = "go-spikes.default:6060",
          __scheme__  = "http",
          __profile_path__ = "/debug/pprof/heap",
          service_name = "go-spikes",
          job = "go-spikes-heap",
          profile_type = "heap",
        },
        {
          __address__ = "go-spikes.default:6060",
          __scheme__  = "http",
          __profile_path__ = "/debug/pprof/goroutine",
          service_name = "go-spikes",
          job = "go-spikes-goroutine",
          profile_type = "goroutine",
        },
      ]

      forward_to = [pyroscope.write.lgtm.receiver]
    }

    pyroscope.write "lgtm" {
      endpoint {
        url = "http://pyroscope:4040"
      }
    }
    