# CROSS-CUTTING START OF otel-metrics CONFIGURATION FOR kafka
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: streaming
  labels:
    app: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:v1.7.0
        ports:
        - containerPort: 9308
          name: metrics
        args:
        - --kafka.server=persistent-cluster-kafka-bootstrap:9092
        - --log.level=info
        - --web.listen-address=:9308
        - --topic.filter=.*
        - --group.filter=.*
        env:
        - name: KAFKA_VERSION
          value: "4.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
# CROSS-CUTTING END OF otel-metrics CONFIGURATION FOR kafka