# CROSS-CUTTING START OF otel-metrics CONFIGURATION FOR mysql
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: db
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-config
  namespace: db
stringData:
  DATA_SOURCE_NAME: "exporter:exporter@tcp(my-mysql-cluster.db.svc.cluster.local:3306)/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.14.0
        ports:
        - containerPort: 9104
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          value: "exporter:exporter@tcp(my-mysql-cluster.db.svc.cluster.local:3306)/"
        args:
        - --collect.info_schema.innodb_metrics
        - --collect.info_schema.processlist
        - --collect.info_schema.query_response_time
        - --collect.info_schema.tables
        - --collect.info_schema.tablestats
        - --collect.global_status
        - --collect.global_variables
        - --collect.slave_status
        - --collect.perf_schema.eventsstatementssum
        - --collect.perf_schema.tablelocks
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
# CROSS-CUTTING END OF otel-metrics CONFIGURATION FOR mysql