# CROSS-CUTTING START OF otel-metrics CONFIGURATION FOR postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: db
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-config
  namespace: db
stringData:
  DATA_SOURCE_NAME: "postgresql://app:app_password@postgres-cluster-rw:5432/myapp?sslmode=require"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-exporter-config
              key: DATA_SOURCE_NAME
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"
        - name: PG_EXPORTER_INCLUDE_DATABASES
          value: "myapp,postgres"
        - name: PG_EXPORTER_DISABLE_DEFAULT_METRICS
          value: "false"
        - name: PG_EXPORTER_DISABLE_SETTINGS_METRICS
          value: "false"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
# CROSS-CUTTING END OF otel-metrics CONFIGURATION FOR postgres