apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: db
data:
  primary.cnf: |
    [mysqld]
    log-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_slave_updates=ON
    
    # Group Replication settings (using loose- prefix to avoid startup errors)
    loose-group_replication_single_primary_mode=ON
    loose-group_replication_enforce_update_everywhere_checks=OFF
    loose-group_replication_group_seeds="mysql-0.mysql-headless.db.svc.cluster.local:33061,mysql-1.mysql-headless.db.svc.cluster.local:33061,mysql-2.mysql-headless.db.svc.cluster.local:33061"
    loose-group_replication_local_address="mysql-0.mysql-headless.db.svc.cluster.local:33061"
    
    # Server ID will be set dynamically
    report_host=mysql-0.mysql-headless.db.svc.cluster.local
    
  replica.cnf: |
    [mysqld]
    log-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_slave_updates=ON
    
    # Group Replication settings (using loose- prefix to avoid startup errors)
    loose-group_replication_single_primary_mode=ON
    loose-group_replication_enforce_update_everywhere_checks=OFF
    loose-group_replication_group_seeds="mysql-0.mysql-headless.db.svc.cluster.local:33061,mysql-1.mysql-headless.db.svc.cluster.local:33061,mysql-2.mysql-headless.db.svc.cluster.local:33061"
    
    # Server ID and local address will be set dynamically
    
  setup-replication.sql: |
    -- Create replication user
    CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY 'repl_password';
    GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
    GRANT BACKUP_ADMIN ON *.* TO 'repl'@'%';
    
    -- Create group replication user
    CREATE USER IF NOT EXISTS 'grp_repl'@'%' IDENTIFIED BY 'grp_repl_password';
    GRANT REPLICATION SLAVE ON *.* TO 'grp_repl'@'%';
    GRANT CONNECTION_ADMIN ON *.* TO 'grp_repl'@'%';
    GRANT BACKUP_ADMIN ON *.* TO 'grp_repl'@'%';
    GRANT GROUP_REPLICATION_STREAM ON *.* TO 'grp_repl'@'%';
    
    -- Create application user
    CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app_password';
    GRANT ALL PRIVILEGES ON *.* TO 'app'@'%';
    
    FLUSH PRIVILEGES;
    
    -- Setup group replication
    SET SQL_LOG_BIN=0;
    CHANGE REPLICATION SOURCE TO SOURCE_USER='grp_repl', SOURCE_PASSWORD='grp_repl_password' FOR CHANNEL 'group_replication_recovery';
    SET SQL_LOG_BIN=1;