apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: db
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 33060
    name: mysql-x
  - port: 33061
    name: group-repl
  clusterIP: None
  selector:
    app: mysql
---
# Primary service - connects through MySQL Router
apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
  namespace: db
  labels:
    app: mysql-router-simple
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 6446
    name: mysql
  - port: 33060
    targetPort: 64460
    name: mysql-x
  selector:
    app: mysql-router-simple
---
# Read-only service - connects through MySQL Router
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: db
  labels:
    app: mysql-router-simple
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 6447
    name: mysql
  - port: 33060
    targetPort: 64470
    name: mysql-x
  selector:
    app: mysql-router-simple
---
# Direct access to cluster instances (for administration)
apiVersion: v1
kind: Service
metadata:
  name: mysql-instances
  namespace: db
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
  - port: 33060
    name: mysql-x
  selector:
    app: mysql