apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-monitor-script
  namespace: db
data:
  monitor-primary.sh: |
    #!/bin/bash
    # This script monitors which MySQL instance is the primary and updates the service
    
    while true; do
      for i in 0 1 2; do
        IS_PRIMARY=$(mysql -h mysql-$i.mysql-headless.db.svc.cluster.local -u root -proot_password -Nse "
          SELECT MEMBER_ROLE FROM performance_schema.replication_group_members 
          WHERE MEMBER_ID = @@server_uuid;" 2>/dev/null | grep -c PRIMARY)
        
        if [[ "$IS_PRIMARY" == "1" ]]; then
          echo "mysql-$i is PRIMARY"
          # Update the mysql-primary service to point only to the current primary
          kubectl patch svc mysql-primary -n db -p '{"spec":{"selector":{"app":"mysql","statefulset.kubernetes.io/pod-name":"mysql-'$i'"}}}'
          break
        fi
      done
      sleep 10
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-primary-monitor
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-primary-monitor
  template:
    metadata:
      labels:
        app: mysql-primary-monitor
    spec:
      serviceAccountName: mysql-monitor
      containers:
      - name: monitor
        image: bitnami/kubectl:latest
        command:
        - bash
        - /scripts/monitor-primary.sh
        volumeMounts:
        - name: monitor-script
          mountPath: /scripts
        env:
        - name: MYSQL_PWD
          value: "root_password"
      volumes:
      - name: monitor-script
        configMap:
          name: mysql-monitor-script
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-monitor
  namespace: db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-monitor
  namespace: db
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-monitor
  namespace: db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-monitor
subjects:
- kind: ServiceAccount
  name: mysql-monitor
  namespace: db