apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-router-config
  namespace: db
data:
  mysqlrouter.conf: |
    [DEFAULT]
    logging_folder = /tmp/log
    runtime_folder = /tmp/run
    data_folder = /tmp/data
    
    [logger]
    level = INFO
    
    [routing:primary]
    bind_address = 0.0.0.0:6446
    destinations = mysql-0.mysql-headless.db.svc.cluster.local:3306
    mode = read-write
    protocol = classic
    
    [routing:secondary]
    bind_address = 0.0.0.0:6447
    destinations = mysql-1.mysql-headless.db.svc.cluster.local:3306,mysql-2.mysql-headless.db.svc.cluster.local:3306
    mode = read-only
    protocol = classic
    
    [routing:x_primary]
    bind_address = 0.0.0.0:64460
    destinations = mysql-0.mysql-headless.db.svc.cluster.local:33060
    mode = read-write
    protocol = x
    
    [routing:x_secondary]
    bind_address = 0.0.0.0:64470
    destinations = mysql-1.mysql-headless.db.svc.cluster.local:33060,mysql-2.mysql-headless.db.svc.cluster.local:33060
    mode = read-only
    protocol = x
    
    [http_server]
    port = 8443
    ssl = 0
    ssl_cert = 
    ssl_key = 
    
    [http_auth_realm:default_auth_realm]
    backend = default_auth_backend
    method = basic
    name = default_realm
    
    [http_auth_backend:default_auth_backend]
    backend = metadata_cache
    
    [rest_api]
    require_realm = default_auth_realm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router-simple
  namespace: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-router-simple
  template:
    metadata:
      labels:
        app: mysql-router-simple
    spec:
      containers:
      - name: mysql-router
        image: mysql/mysql-router:8.0
        command:
        - bash
        - -c
        - |
          mkdir -p /tmp/log /tmp/run /tmp/data
          exec mysqlrouter --config /etc/mysqlrouter/mysqlrouter.conf
        ports:
        - containerPort: 6446
          name: rw-port
        - containerPort: 6447
          name: ro-port
        - containerPort: 64460
          name: x-rw-port
        - containerPort: 64470
          name: x-ro-port
        - containerPort: 8443
          name: rest-port
        volumeMounts:
        - name: config
          mountPath: /etc/mysqlrouter
        livenessProbe:
          tcpSocket:
            port: 6446
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6446
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: mysql-router-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-router-simple
  namespace: db
spec:
  selector:
    app: mysql-router-simple
  ports:
  - port: 6446
    targetPort: 6446
    name: mysql-rw
  - port: 6447
    targetPort: 6447
    name: mysql-ro