apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
      - name: pyroscope
        image: grafana/pyroscope:main-6d0f426
        ports:
        - containerPort: 4040
          name: http
        env:
        - name: PYROSCOPE_ANALYTICS_REPORTING_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: observability
spec:
  selector:
    app: pyroscope
  ports:
  - name: http
    port: 4040
    targetPort: 4040
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: observability
data:
  config.yaml: |
    analytics:
      reporting_enabled: false
    
    server:
      http_listen_port: 4040