# PostgreSQL Cluster Configuration using CloudNativePG
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: db
spec:
  # Number of instances (1 primary + 2 replicas)
  instances: 3
  
  # PostgreSQL version
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  
  # Primary update strategy
  primaryUpdateStrategy: unsupervised
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "8MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"
      max_parallel_maintenance_workers: "4"
      
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: myapp
      owner: app
      secret:
        name: postgres-app-secret
      
  # Storage configuration
  storage:
    size: 10Gi
    storageClass: standard
    
  # Resources
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
      
  # Monitoring
  monitoring:
    enabled: false
    
  # High Availability configuration
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
    
  # Connection pooling with PgBouncer
  pooler:
    enabled: true
    type: pgbouncer
    instances: 2
    pgbouncer:
      poolMode: session
      parameters:
        max_client_conn: "1000"
        default_pool_size: "25"
        
  # Service configuration
  service:
    type: ClusterIP
    
---
# Secret for application user
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: db
type: Opaque
stringData:
  username: app
  password: app_password
  
---
# Secret for superuser (optional, for admin access)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-secret
  namespace: db
type: Opaque
stringData:
  username: postgres
  password: postgres-root-password