apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db
data:
  patroni.yml: |
    scope: postgres-cluster
    namespace: db
    name: "{POD_NAME}"

    restapi:
      listen: 0.0.0.0:8008
      connect_address: "{POD_IP}:8008"

    etcd:
      hosts: postgres-etcd:2379

    bootstrap:
      dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        master_start_timeout: 300
        synchronous_mode: false
        postgresql:
          use_pg_rewind: true
          use_slots: true
          parameters:
            max_connections: 100
            shared_buffers: 256MB
            effective_cache_size: 1GB
            maintenance_work_mem: 64MB
            checkpoint_completion_target: 0.7
            wal_buffers: 16MB
            default_statistics_target: 100
            random_page_cost: 1.1
            effective_io_concurrency: 200
            work_mem: 4MB
            min_wal_size: 1GB
            max_wal_size: 2GB
            max_worker_processes: 2
            max_parallel_workers_per_gather: 1
            max_parallel_workers: 2
            max_replication_slots: 10
            max_wal_senders: 10
            wal_level: replica
            hot_standby: "on"
            wal_log_hints: "on"
            archive_mode: "off"
            archive_timeout: 1800s
            shared_preload_libraries: "pg_stat_statements"

      initdb:
        - encoding: UTF8
        - data-checksums

      pg_hba:
        - local all all trust
        - host all all 127.0.0.1/32 trust
        - host all all ::1/128 trust
        - local replication all trust
        - host replication all 127.0.0.1/32 trust
        - host replication all ::1/128 trust
        - host all all all md5
        - host replication all all md5

      users:
        admin:
          password: admin_password
          options:
            - createrole
            - createdb
        app:
          password: app_password
          options:
            - createdb

    postgresql:
      listen: 0.0.0.0:5432
      connect_address: "{POD_IP}:5432"
      data_dir: /var/lib/postgresql/data
      pgpass: /tmp/pgpass
      authentication:
        replication:
          username: replicator
          password: repl_password
        superuser:
          username: postgres
          password: postgres_password
      parameters:
        unix_socket_directories: '/var/run/postgresql'
      create_replica_methods:
        - basebackup
      basebackup:
        max-rate: 100M
        checkpoint: fast

    watchdog:
      mode: automatic
      device: /dev/watchdog
      safety_margin: 5

    tags:
      nofailover: false
      noloadbalance: false
      clonefrom: false
      nosync: false