apiVersion: v1
kind: Service
metadata:
  name: postgres-etcd
  namespace: db
spec:
  ports:
  - port: 2379
    targetPort: 2379
    name: client
  - port: 2380
    targetPort: 2380
    name: peer
  selector:
    app: postgres-etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-etcd
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-etcd
  template:
    metadata:
      labels:
        app: postgres-etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.9
        command:
        - etcd
        - --name=etcd0
        - --data-dir=/etcd-data
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://postgres-etcd:2379
        - --listen-peer-urls=http://0.0.0.0:2380
        - --initial-advertise-peer-urls=http://postgres-etcd:2380
        - --initial-cluster=etcd0=http://postgres-etcd:2380
        - --initial-cluster-state=new
        - --initial-cluster-token=postgres-cluster
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: etcd-data
        emptyDir: {}