apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-label-updater
  namespace: db
data:
  update-labels.sh: |
    #!/bin/bash
    set -e
    
    while true; do
      echo "Checking Patroni cluster state..."
      
      # Get all postgres pods
      for i in 0 1 2; do
        POD_NAME="postgres-$i"
        
        # Check if pod exists and is ready
        if kubectl get pod $POD_NAME -n db &>/dev/null; then
          # Get Patroni status
          ROLE=$(kubectl exec -n db $POD_NAME -c postgres -- curl -s http://localhost:8008 | python3 -c "import sys, json; data = json.load(sys.stdin); print(data.get('role', 'unknown'))" 2>/dev/null || echo "error")
          
          if [ "$ROLE" = "master" ]; then
            echo "$POD_NAME is master"
            kubectl label pod $POD_NAME -n db role=master spilo-role=master --overwrite
          elif [ "$ROLE" = "replica" ]; then
            echo "$POD_NAME is replica"
            kubectl label pod $POD_NAME -n db role=replica spilo-role=replica --overwrite
          else
            echo "$POD_NAME role unknown or error"
          fi
        fi
      done
      
      sleep 5
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-label-updater
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-label-updater
  template:
    metadata:
      labels:
        app: postgres-label-updater
    spec:
      serviceAccountName: postgres-label-updater
      containers:
      - name: updater
        image: bitnami/kubectl:latest
        command:
        - bash
        - /scripts/update-labels.sh
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: postgres-label-updater
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-label-updater
  namespace: db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-label-updater
  namespace: db
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-label-updater
  namespace: db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-label-updater
subjects:
- kind: ServiceAccount
  name: postgres-label-updater
  namespace: db