apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: db
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  - name: patroni
    port: 8008
    targetPort: 8008
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: db
  labels:
    app: postgres
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: db
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-all
  namespace: db
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    app: postgres