apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: db
spec:
  serviceName: postgres-headless
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql-repmgr:15
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRESQL_POSTGRES_PASSWORD
          value: postgres_password
        - name: POSTGRESQL_USERNAME
          value: app
        - name: POSTGRESQL_PASSWORD
          value: app_password
        - name: POSTGRESQL_DATABASE
          value: postgres
        - name: REPMGR_USERNAME
          value: repmgr
        - name: REPMGR_PASSWORD
          value: repmgr_password
        - name: REPMGR_DATABASE
          value: repmgr
        - name: REPMGR_PRIMARY_HOST
          value: postgres-0.postgres-headless.db.svc.cluster.local
        - name: REPMGR_PRIMARY_PORT
          value: "5432"
        - name: REPMGR_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPMGR_NODE_NETWORK_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPMGR_PARTNER_NODES
          value: postgres-0.postgres-headless.db.svc.cluster.local,postgres-1.postgres-headless.db.svc.cluster.local,postgres-2.postgres-headless.db.svc.cluster.local
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BITNAMI_DEBUG
          value: "false"
        - name: POSTGRESQL_CLUSTER_APP_NAME
          value: postgres-cluster
        - name: POSTGRESQL_ENABLE_TLS
          value: "no"
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "true"
        - name: POSTGRESQL_LOG_CONNECTIONS
          value: "true"
        - name: POSTGRESQL_LOG_DISCONNECTIONS
          value: "true"
        - name: POSTGRESQL_PGAUDIT_LOG
          value: "false"
        - name: POSTGRESQL_LOG_LINE_PREFIX
          value: "%t [%p] %q%u@%d "
        - name: POSTGRESQL_LOG_TIMEZONE
          value: "UTC"
        - name: POSTGRESQL_ENABLE_LOG_REPLICATION
          value: "true"
        - name: POSTGRESQL_ENABLE_LOG_STANDBY
          value: "true"
        - name: PGUSER
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres_password"
        - name: PGDATABASE
          value: "postgres"
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: pgdata
          mountPath: /bitnami/postgresql
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - |
                pg_isready -U postgres -d postgres -q && \
                psql -U postgres -d postgres -c "SELECT 1" > /dev/null 2>&1
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - |
                pg_isready -U postgres -d postgres -q && \
                repmgr node check --role 2>/dev/null | grep -E 'primary|standby' > /dev/null
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi