apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        # Annotations for identification
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: sample-app:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 6060
          name: pprof
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "alloy.observability:4317"
        - name: OTEL_SERVICE_NAME
          value: "sample-app"
        - name: PYROSCOPE_ADDRESS
          value: "http://lgtm.observability:4040"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: default
spec:
  selector:
    app: sample-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: pprof
    port: 6060
    targetPort: 6060
  type: ClusterIP